### ISSUE TITLE
Any idea how start this project?

### ISSUE THREAD

**Issue by malliwi88** [kriskbx/gitlab-time-tracker-taskbar#1]
Hello I'm interested in collaborate.

**Comment by kriskbx** [comment]
There will be a closed beta test within the next weeks. I'm aiming for a release (Ubuntu Store, Apple App Store, Microsoft Store) in the first quarter of 2018. I'm gonna open the source code after release under a license that still allows me to earn some money in the stores. Contributions are very welcome and appreciated after the inital release. For now: thank you so much for your interest and I will keep you up to date here. :)

**Comment by kriskbx** [comment]
I got the first beta packages ready for Mac and Linux. Drop me a line to gtt at kris dot cool an I will send you the private link back. No worries, after a first closed beta I will open the code to everyone.

**Comment by kriskbx** [comment]
I case you're still interested. Packages are available from the release-page of this repository.
