### ISSUE TITLE
Windows scaling/positioning

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#10]
The app does not use the right scaling/position (it uses the 250% scaling from the bottom screen on the top screens), and it is not positioned above the actual icon.

Not sure what you can do about it, but I just wanted to let you know :)

![image](https://user-images.githubusercontent.com/1835343/41490499-a3abf8cc-70f4-11e8-8c7c-d0d031238da1.png)

**Comment by bobvandevijver** [comment]
When the large 4K screen is set as primary, the tool is positioned correctly in normal size, so that would be a perfect workaround for me

**Comment by kriskbx** [comment]
Sorry, I can't try it out due to the lack of monitors around here, but it should be fixed with #8. Can you upgrade and try again?

**Comment by bobvandevijver** [comment]
Couldn't check this due to #20

**Comment by bobvandevijver** [comment]
This is indeed fixed in 0.3.0 👍
