### ISSUE TITLE
Log interface does not show correct times

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#11]
As you can see in the image, the logged time is 1h 4m, but the start and end time are the same (they are actually both the end time).

![image](https://user-images.githubusercontent.com/1835343/41490478-8e21d60c-70f4-11e8-882b-c9d3997a124b.png)

**Comment by kriskbx** [comment]
Fixed in 0.2.5. Thanks for pointing it out!
