### ISSUE TITLE
Time data is not synced on Windows

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#13]
The tools just keeps 'syncing', but does do anything:

![image](https://user-images.githubusercontent.com/1835343/41489946-18eff19a-70f2-11e8-879f-b519cc3f767b.png)

Pausing and resuming has no effect, restarting the application does make sync happen.

**Comment by bobvandevijver** [comment]
It seems like it does work now. Might be caused by missing configuration during that instances startup.

**Comment by kriskbx** [comment]
This happened most probably because of an error in the underlying gtt cli. It should be fixed by now. If the error still occurs, feel free to open the issue!
