### ISSUE TITLE
Project list disappears behind the taskbar

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#15]
Of the 13 available projects, I can only see 6 (including the scrolled one), due to the fact that the rest is hidden behind the taskbar.

![image](https://user-images.githubusercontent.com/1835343/41490418-4cf3b920-70f4-11e8-93f6-a57d8fe27e99.png)

**Comment by bobvandevijver** [comment]
This still happens with the latest version (0.3.0)

**Comment by kriskbx** [comment]
Fixed in 0.3.1. Thanks for pointing this out. Was quite a challenge to find a proper solution to this. :)

**Comment by bobvandevijver** [comment]
I cannot test is now, as there is no installer for windows on 0.3.1. But it looks like you're already working on that!

**Comment by kriskbx** [comment]
Yeah, AppVeyor refuses to build stuff... 😄 I'm on it!

**Comment by kriskbx** [comment]
Good news: I fixed Windows CI. Packages are beeing built right now. 😄

**Comment by bobvandevijver** [comment]
Well, I hate to say it, but I don't see them 😢

**Comment by kriskbx** [comment]
I'm testing all the CI stuff on a virtual machine, but AppVeyor is doing things different (again). Packages are now pushed to GitHub releases. Sorry for the inconvenience.

**Comment by bobvandevijver** [comment]
Confirmed fixed 😄
