### ISSUE TITLE
2.6.0 on Windows crashes at start

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#20]
See screenshot:

![schermafdruk 2018-08-09 20 19 54](https://user-images.githubusercontent.com/1835343/43917836-a70893ac-9c11-11e8-837e-ef8eeac110c4.png)

Note that this is a clean installation.

**Comment by kriskbx** [comment]
I just released 0.3.0 (will take some time until packages are built) which should fix this. I recently changed my system and I can't test it right now on Windows but I fixed the error for Mac and Linux. So I guess it's fixed on Win too. :)

**Comment by bobvandevijver** [comment]
Confirmed 👍
