### ISSUE TITLE
Distributing Linux builds for Arch and Ubuntu using their package managers

### ISSUE THREAD

**Issue by naturallymitchell** [kriskbx/gitlab-time-tracker-taskbar#30]
Do you already plan to do this?  Do you need any more info?

This would really be great to ease installation procedure.

**Comment by kriskbx** [comment]
I will do that eventually. Personally I'm favoring snapcraft.io because it's available for a vast number of platforms and easy to use.

**Comment by kriskbx** [comment]
Continue in #22
