### ISSUE TITLE
Guard 'publish' build task with option

### ISSUE THREAD

**Issue by kenny-evitt** [kriskbx/gitlab-time-tracker-taskbar#33]
I was able to build the project (I think) after installing Yarn and then running the *build.sh* script. But the script failed at the final 'publish' Yarn task:

```bash
kevitt@LT-NYC123 MINGW64 /c/@code/gitlab-time-tracker-taskbar (master)
$ ./build.sh
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
...
√ Packaging Application
Making for the following targets:
√ Making for target: squirrel - On platform: win32 - For arch: x64
√ Resolving publish target: github

Electron forge was terminated:
Please set GITHUB_TOKEN in your environment to access these features
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I adapted some code from another Bash script that adds a `--publish` to *build.sh*. I'll submit a PR for this shortly.

**Comment by kenny-evitt** [comment]
Pull request:

 - [Guard publish task with option by kenny-evitt · Pull Request #34 · kriskbx/gitlab-time-tracker-taskbar](https://github.com/kriskbx/gitlab-time-tracker-taskbar/pull/34)

**Comment by kriskbx** [comment]
The `build.sh` is only meant to be run by the CI-Server. I won't accept your PR as it breaks the pipeline.

What exactly do you want to accomplish here?

**Comment by kenny-evitt** [comment]
@kriskbx I figured *build.sh* was also used for local builds. I wanted to look into some of the other issues I had like gitlab-time-tracker#75 so I cloned this repo and figured running *build.sh* was necessary to run a local build.

**Comment by kriskbx** [comment]
Just run `yarn package` to create a build locally or `yarn start` to simply start the application. :)

**Comment by kenny-evitt** [comment]
@kriskbx Thanks!

**Comment by kriskbx** [comment]
You're welcome. I'm sorry that there's no documentation yet, still working on it.
