### ISSUE TITLE
Doesn't work on ubuntu 18.10, widget in the middle of the screen

### ISSUE THREAD

**Issue by Turboconnard** [kriskbx/gitlab-time-tracker-taskbar#35]
Hi, 
I installed release .deb file with no problems. The program is installed, i can even configure it and sync it with my gitlab. 
The only problem is that the widget launchs itself in the middle of the screen and never appears in the task bar...

I downloaded the source and compiled it myself: same problem.

![image](https://user-images.githubusercontent.com/140588/48337348-054ec800-e663-11e8-8c0c-6cfb30c09171.png)

**Comment by dm0** [comment]
Try TopIcons Plus extension: https://extensions.gnome.org/extension/1031/topicons/

**Comment by Turboconnard** [comment]
thank you ! it works ;)
